global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 5s
    #    basic_auth:
    #      username: ${PROMETHEUS_USERNAME}
    #      password: ${PROMETHEUS_PASSWORD}
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'booking-cinema-tickets'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'host-metrics'

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-metrics'