server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    backoff_config:
      min_period: 1s
      max_period: 5m
      max_retries: 10
    timeout: 10s
    batchwait: 1s
    batchsize: 1048576

scrape_configs:
  - job_name: spring-boot-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot-logs
          app: booking-cinema-tickets
          env: ${ACTIVE_PROFILE:-default}
          __path__: /var/log/app/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            thread: thread
            logger: logger
            traceId: traceId
            userId: userId
            sessionId: sessionId
            clientIp: clientIp
            env: env
            message: message
            version: version
            hostname: hostname
      - labels:
          level:
          thread:
          logger:
          env:
          hostname:
      - timestamp:
          source: timestamp
          format: 2006-01-02 15:04:05.000